# -*- coding: utf-8 -*-
"""Project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIQBrHayzovUj6eA86ZM1odR3QbPlNZ-
"""

from google.colab import files
files.upload()

import pandas as pd
df=pd.read_csv("/content/text.csv")

df.head()

df.tail()

df.shape

# label=>output variable
# Six categories: sadness (0), joy (1), love (2), anger (3), fear (4), and surprise (5).

import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('punkt_tab')

import pandas as pd
import re
import string
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

#reduce word to its base form
lemmatizer = WordNetLemmatizer()

#words like "the", "is", "at", "which"
stop_words = set(stopwords.words('english'))

def pre_process(text):
  text=text.lower()

#Uses a translation table to remove all punctuation marks (like !, ?, .) from the string.
  text=text.translate(str.maketrans('','',string.punctuation))

  tokens = word_tokenize(text)
  cleaned_tokens=[]
  for word in tokens:
    if word not in stop_words:
      #For the remaining words, it uses lemmatizer.lemmatize(word, pos='v'). This reduces words to their base or dictionary form(running to run)
      cleaned_tokens.append(lemmatizer.lemmatize(word,pos='v'))

  return " ".join(cleaned_tokens)

df['cleaned_text'] = df['text'].apply(pre_process)

df.head()

df.tail()

df.isnull().sum()

df.columns

df['label'].value_counts()

import numpy as np
from sklearn.utils import class_weight

# 1. Calculate the weights based on your 'label' column
weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(df['label']),
    y=df['label']
)

# 2. Convert to a dictionary
class_weights_dict = dict(zip(np.unique(df['label']), weights))

print(f"Calculated weights: {class_weights_dict}")

from sklearn.model_selection import train_test_split

# X = the text you want to learn from, y = the label you want to predict
X = df['cleaned_text']
y = df['label']

# Split: 80% for training, 20% for testing
# 'stratify=y' is critical for your imbalanced data!
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize the vectorizer
tfidf = TfidfVectorizer(max_features=3000, ngram_range=(1,2))

# Transform your text into numbers
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

from sklearn.linear_model import LogisticRegression

# 'balanced' weights handle your imbalanced label counts automatically
model = LogisticRegression(class_weight='balanced', max_iter=1000)
model.fit(X_train_tfidf, y_train)

print("Model training complete!")

from sklearn.metrics import classification_report, accuracy_score

# Generate predictions on the test set
y_pred = model.predict(X_test_tfidf)

# Print overall accuracy
print(f"Overall Accuracy: {accuracy_score(y_test, y_pred):.2%}")

# Print detailed report for each class (0-5)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# 1. Create the matrix data
cm = confusion_matrix(y_test, y_pred)

# 2. Plot the "Heatmap"
plt.figure(figsize=(10, 7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Label 0', 'Label 1', 'Label 2', 'Label 3', 'Label 4', 'Label 5'],
            yticklabels=['Label 0', 'Label 1', 'Label 2', 'Label 3', 'Label 4', 'Label 5'])

plt.xlabel('Predicted Label (What the model guessed)')
plt.ylabel('True Label (The actual answer)')
plt.title('Emotion Classification Confusion Matrix')
plt.show()

"""#  Finding The Mistakes

**Label 1 vs. Label 2**: Look at row "Label 1." The model guessed "Label 2" wrongly 2,302 times. This suggests the text in Label 1 and Label 2 might be very similar or share common words.

**Label 4 vs. Label 5:** The model guessed "Label 5" for a "Label 4" text 801 times.
"""

import numpy as np

# 1. Get the indices where the True Label is 1 BUT the Predicted Label is 2
# Note: Ensure y_test and y_pred are converted to numpy arrays first
y_test_arr = np.array(y_test)
mistake_indices = np.where((y_test_arr == 1) & (y_pred == 2))[0]

# 2. Print the first 5 text examples from those indices
print(f"Total mistakes found: {len(mistake_indices)}\n")
print("Top 5 examples of True Label 1 being predicted as Label 2:")
print("-" * 30)

for i in mistake_indices[:5]:
    # Use .iloc if X_test is a pandas Series
    original_text = X_test.iloc[i]
    print(f"Text: {original_text}")
    print("-" * 30)

"""Feel and bless Almost all mistaken

"""

mistakes = []

for i in range(len(X_test)):
    if "bless" in X_test.iloc[i] and y_test.iloc[i] != y_pred[i]:
        mistakes.append((X_test.iloc[i],
                         y_test.iloc[i],
                         y_pred[i]))

for m in mistakes[:5]:
    print(m)

from collections import Counter
# get misclassified texts (Label 1 predicted as Label 2)
mis_texts =[X_test.iloc[i] for i in mistake_indices]
all_words="".join(mis_texts).split()
common_words=Counter(all_words).most_common(20)
print("most common words in misclassified samples:")
print(common_words)

vectorizer=TfidfVectorizer(max_features=7000,ngram_range=(1,2))

vectorizer=TfidfVectorizer(max_features=10000)

model=LogisticRegression(class_weight='balanced')

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(X)

"""***SVM***"""

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

# Initialize SVM model
svm_model = LinearSVC(
    class_weight=class_weights_dict,
    random_state=42
)

# Train model
svm_model.fit(X_train_tfidf, y_train)

# Predict
y_pred = svm_model.predict(X_test_tfidf)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

# Import required libraries
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Create confusion matrix using actual labels and predicted labels
cm = confusion_matrix(y_test, y_pred)

# Display the confusion matrix in graphical form
disp = ConfusionMatrixDisplay(confusion_matrix=cm)

# Plot the confusion matrix
disp.plot()

# Show the plot
plt.show()

# Import library used for saving models
import joblib

# Save the trained SVM model
joblib.dump(svm_model, "svm_model.pkl")

# Save the TF-IDF vectorizer
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

# Load saved model
model = joblib.load("svm_model.pkl")

# Load TF-IDF vectorizer
vectorizer = joblib.load("tfidf_vectorizer.pkl")

# Example new text
sample_text = ["paid electricity bill"]

# Convert text to TF-IDF features
sample_vector = tfidf.transform(sample_text)

# Predict category
prediction = svm_model.predict(sample_vector)

print("Predicted label:", prediction)

# Map numeric labels to emotion names
label_map = {
    0: "sadness",
    1: "joy",
    2: "love",
    3: "anger",
    4: "fear",
    5: "surprise"
}

# Modified prediction function
def predict_text(text):

    # Convert input text to TF-IDF features
    text_vector = tfidf.transform([text])

    # Predict numeric label
    prediction = svm_model.predict(text_vector)[0]

    # Convert numeric label to emotion name
    return label_map[prediction]


# Test the function
print(predict_text("restaurant payment"))

texts = [
    "I am very happy today",
    "I feel scared and nervous",
    "This made me so angry",
    "I love spending time with my family",
    "I am shocked by the news"
]

for t in texts:
    print(t, "→", predict_text(t))

texte=["I am frustrated"]
for t in texte:
  print(t, "->" , predict_text(t))

"""# Task
Evaluate model performance using `sklearn.metrics.classification_report`, illustrate hyperparameter tuning for the SVM model, analyze prediction errors by showing examples of incorrect predictions, create an interactive function for new text predictions, and summarize the findings.
"""

import joblib
from sklearn.metrics import classification_report

# Load saved model
svm_model = joblib.load("svm_model.pkl")

# Load TF-IDF vectorizer
tfidf = joblib.load("tfidf_vectorizer.pkl")

# Assuming X_test and y_test are available from a previous data splitting step
# If they are not available, this code will raise an error.

# Transform the X_test data using the loaded tfidf vectorizer
X_test_vectorized = tfidf.transform(X_test)

# Use the loaded svm_model to make predictions on X_test_vectorized
y_pred = svm_model.predict(X_test_vectorized)

# Define the label_map from the notebook state for better readability
label_map = {
    0: "sadness",
    1: "joy",
    2: "love",
    3: "anger",
    4: "fear",
    5: "surprise"
}

# Print the classification report
print(classification_report(y_test, y_pred, target_names=label_map.values()))

"""## Explore Hyperparameter Tuning

### Subtask:
Illustrate how to set up hyperparameter tuning for the SVM model using techniques like GridSearchCV or RandomizedSearchCV to systematically search for optimal model parameters. No need to run the full grid search, just illustrate the concept.

"""

from sklearn.model_selection import GridSearchCV
from sklearn.svm import LinearSVC

# Assuming svm_model is already loaded or initialized from previous steps
# If starting fresh, we would initialize it as:
# svm_model = LinearSVC(random_state=42, class_weight=class_weights_dict)

# Define the parameter grid for LinearSVC
param_grid = {
    'C': [0.1, 1, 10, 100],
    'loss': ['hinge', 'squared_hinge'],
    'dual': [True, False] # 'dual=False' is often preferred for large datasets, 'dual=True' is default
}

# Instantiate GridSearchCV
# We'll use the already trained svm_model or instantiate a new one for tuning
# For illustration, let's assume we are using the 'svm_model' variable for clarity
# In a real scenario, you might instantiate a new LinearSVC here if you want to tune independently

grid_search = GridSearchCV(
    estimator=LinearSVC(random_state=42, class_weight=class_weights_dict, max_iter=2000),
    param_grid=param_grid,
    cv=5,
    scoring='f1_weighted',
    verbose=2,
    n_jobs=-1 # Use all available CPU cores
)

print("GridSearchCV setup complete. The object 'grid_search' is ready for fitting.")
print("Parameters to tune:")
for param, values in param_grid.items():
    print(f"  {param}: {values}")

"""## Analyze Prediction Errors

### Subtask:
Identify and display a few examples of text messages from the test set where the model made incorrect predictions.

"""

import numpy as np

# 1. Convert y_test and y_pred into NumPy arrays
y_test_arr = np.array(y_test)
y_pred_arr = np.array(y_pred)

# 2. Find the indices where y_test does not match y_pred
misclassified_indices = np.where(y_test_arr != y_pred_arr)[0]

# 3. Create a dictionary label_map
label_map = {
    0: "sadness",
    1: "joy",
    2: "love",
    3: "anger",
    4: "fear",
    5: "surprise"
}

print(f"Total misclassified samples: {len(misclassified_indices)}\n")
print("Examples of incorrect predictions:")
print("-" * 50)

# 4. Iterate through a few (e.g., 5) of these misclassified indices
for i, idx in enumerate(misclassified_indices[:5]): # Display first 5 examples
    # 5. Print the original text, true label, and predicted label
    original_text = X_test.iloc[idx]
    true_label = label_map[y_test_arr[idx]]
    predicted_label = label_map[y_pred_arr[idx]]

    print(f"Text: {original_text}")
    print(f"True Label: {true_label}")
    print(f"Predicted Label: {predicted_label}")
    print("-" * 50)

"""# Task
The task is to summarize the findings from the emotion classification model and present the interactive prediction function. This includes:

1.  **Summarizing Model Performance**: Detail the key metrics from the classification report, specifically highlighting the overall accuracy and the precision, recall, and f1-score for each emotion class.
2.  **Hyperparameter Tuning Insights**: Explain the concept of hyperparameter tuning using GridSearchCV for the SVM model, as illustrated in the notebook, without actually running the full grid search.
3.  **Error Analysis Observations**: Discuss the insights gained from analyzing prediction errors, including common misclassifications and frequently occurring words in misclassified samples.
4.  **Interactive Prediction Function**: Present the interactive prediction function that allows users to input text and receive an emotion prediction, showcasing its functionality with example inputs.

## Create Interactive Prediction Function

### Subtask:
Develop an interactive function that takes user input text, preprocesses it using the loaded TF-IDF vectorizer, and then predicts the emotion using the trained SVM model. The function should also map the numeric prediction to its corresponding emotion name for a user-friendly output.
"""

def predict_emotion(text):
    # Preprocess the input text using the loaded TF-IDF vectorizer
    # Note: text must be passed as a list for transform method
    text_vectorized = tfidf.transform([text])

    # Predict the numeric emotion label using the trained SVM model
    numeric_prediction = svm_model.predict(text_vectorized)[0]

    # Map the numeric label to its corresponding emotion name
    emotion_name = label_map[numeric_prediction]

    return emotion_name

# Demonstrate the function with example texts
example_texts = [
    "I feel wonderful today, full of joy and happiness",
    "This is so frustrating, I can't believe this happened",
    "I am scared of the dark and loud noises",
    "I love spending time with my family and friends",
    "I was completely surprised by the news",
    "I feel a deep sadness after watching that movie"
]

print("Emotion predictions for example texts:")
print("-------------------------------------")
for text in example_texts:
    predicted_emotion = predict_emotion(text)
    print(f"Text: '{text}'\nPredicted Emotion: {predicted_emotion}\n")

import numpy as np

# Convert y_test and y_pred into NumPy arrays if not already done
y_test_arr = np.array(y_test)
y_pred_arr = np.array(y_pred)

# Find the indices where the true label is 'joy' (1) AND the predicted label is 'love' (2)
misclassified_joy_as_love_indices = np.where((y_test_arr == 1) & (y_pred_arr == 2))[0]

# Extract the corresponding text samples from X_test
joy_as_love_misclassified_texts = X_test.iloc[misclassified_joy_as_love_indices].tolist()

print(f"Total texts where True Label was 'joy' and Predicted Label was 'love': {len(joy_as_love_misclassified_texts)}")
print("\nFirst 5 examples of such misclassified texts:")
for text in joy_as_love_misclassified_texts[:5]:
    print(f"- {text}")

"""**Reasoning**:
Now that the misclassified texts (joy predicted as love) have been extracted, the next step is to analyze the common words and N-grams within these texts to identify patterns that might lead to misclassification. This will help us understand why the model confused these two emotions.


"""

from collections import Counter
from nltk.util import ngrams

# Join all misclassified texts into a single string
all_misclassified_text = " ".join(joy_as_love_misclassified_texts)

# Tokenize the combined text into words
words = all_misclassified_text.split()

# Calculate word frequency
word_counts = Counter(words)
print("\nMost common words in 'joy' texts misclassified as 'love':")
print(word_counts.most_common(20))

# Calculate bigram (2-word sequence) frequency
bigrams = list(ngrams(words, 2))
bigram_counts = Counter(bigrams)
print("\nMost common bigrams in 'joy' texts misclassified as 'love':")
print(bigram_counts.most_common(20))

"""## Display Examples of Misclassifications

### Subtask:
Display a few examples of the `cleaned_text` samples where the true label was 'joy' (1) but the model incorrectly predicted 'love' (2), along with their true and predicted labels.
"""

print("\nExamples of 'joy' texts misclassified as 'love':")
print("-" * 50)

# Display a few examples (e.g., 5) of these misclassified texts
for i, idx in enumerate(misclassified_joy_as_love_indices[:5]):
    original_text = X_test.iloc[idx]
    true_label = label_map[y_test_arr[idx]]
    predicted_label = label_map[y_pred_arr[idx]]

    print(f"Text: {original_text}")
    print(f"True Label: {true_label}")
    print(f"Predicted Label: {predicted_label}")
    print("-" * 50)

"""## Summarize Misclassification Insights

### Subtask:
Based on the common words, N-grams, and examples, summarize the key linguistic characteristics or sentiments that lead the model to confuse 'joy' with 'love'. This will explain why these misclassifications occur.

# Task
```python
def predict_emotion(text):
    # Preprocess the input text using the loaded TF-IDF vectorizer
    # Note: text must be passed as a list for transform method
    text_vectorized = tfidf.transform([text])

    # Predict the numeric emotion label using the trained SVM model
    numeric_prediction = svm_model.predict(text_vectorized)[0]

    # Map the numeric label to its corresponding emotion name
    emotion_name = label_map[numeric_prediction]

    return emotion_name
```

## Display Prediction Function

### Subtask:
Display the code for the `predict_emotion` function, which takes text input, preprocesses it, and predicts the emotion using the trained SVM model.
"""

def predict_emotion(text):
    # Preprocess the input text using the loaded TF-IDF vectorizer
    # Note: text must be passed as a list for transform method
    text_vectorized = tfidf.transform([text])

    # Predict the numeric emotion label using the trained SVM model
    numeric_prediction = svm_model.predict(text_vectorized)[0]

    # Map the numeric label to its corresponding emotion name
    emotion_name = label_map[numeric_prediction]

    return emotion_name

print("The 'predict_emotion' function has been defined.")

"""## Demonstrate Interactive Prediction

### Subtask:
Provide examples of how to use the `predict_emotion` function with various text inputs to show its interactive capabilities and the predicted emotions.

"""

def predict_emotion(text):
    # Preprocess the input text using the loaded TF-IDF vectorizer
    # Note: text must be passed as a list for transform method
    text_vectorized = tfidf.transform([text])

    # Predict the numeric emotion label using the trained SVM model
    numeric_prediction = svm_model.predict(text_vectorized)[0]

    # Map the numeric label to its corresponding emotion name
    emotion_name = label_map[numeric_prediction]

    return emotion_name

# Demonstrate the function with example texts
example_texts = [
    "I feel wonderful today, full of joy and happiness",
    "This is so frustrating, I can't believe this happened",
    "I am scared of the dark and loud noises",
    "I love spending time with my family and friends",
    "I was completely surprised by the news",
    "I feel a deep sadness after watching that movie"
]

print("Emotion predictions for example texts:")
print("-------------------------------------")
for text in example_texts:
    predicted_emotion = predict_emotion(text)
    print(f"Text: '{text}' -> Predicted Emotion: {predicted_emotion}\n")

"""## Identify Correctly Classified 'Joy' Texts

### Subtask:
Filter the test set (X_test) to identify texts where the true label (y_test) is 'joy' (1) and the predicted label (y_pred) is also 'joy' (1). Store these texts for further analysis.

"""

import numpy as np

# 1. Convert y_test and y_pred into NumPy arrays if not already done
y_test_arr = np.array(y_test)
y_pred_arr = np.array(y_pred)

# 2. Find the indices where both the true label is 'joy' (1) AND the predicted label is 'joy' (1)
correctly_classified_joy_indices = np.where((y_test_arr == 1) & (y_pred_arr == 1))[0]

# 3. Extract the corresponding text samples from X_test
correctly_classified_joy_texts = X_test.iloc[correctly_classified_joy_indices].tolist()

print(f"Total texts correctly classified as 'joy': {len(correctly_classified_joy_texts)}")
print("\nFirst 5 examples of correctly classified 'joy' texts:")
for text in correctly_classified_joy_texts[:5]:
    print(f"- {text}")

from collections import Counter
from nltk.util import ngrams

# Join all correctly classified 'joy' texts into a single string
all_correct_joy_text = " ".join(correctly_classified_joy_texts)

# Tokenize the combined text into words
words_joy = all_correct_joy_text.split()

# Calculate word frequency
word_counts_joy = Counter(words_joy)
print("\nMost common words in correctly classified 'joy' texts:")
print(word_counts_joy.most_common(20))

# Calculate bigram (2-word sequence) frequency
bigrams_joy = list(ngrams(words_joy, 2))
bigram_counts_joy = Counter(bigrams_joy)
print("\nMost common bigrams in correctly classified 'joy' texts:")
print(bigram_counts_joy.most_common(20))

"""### 4. Interactive Prediction Function

The `predict_emotion` function takes a text input, preprocesses it using the trained TF-IDF vectorizer, and then uses the loaded SVM model to predict the emotion. The numeric prediction is then mapped to a user-friendly emotion name.

```python
def predict_emotion(text):
    # Preprocess the input text using the loaded TF-IDF vectorizer
    # Note: text must be passed as a list for transform method
    text_vectorized = tfidf.transform([text])

    # Predict the numeric emotion label using the trained SVM model
    numeric_prediction = svm_model.predict(text_vectorized)[0]

    # Map the numeric label to its corresponding emotion name
    emotion_name = label_map[numeric_prediction]

    return emotion_name
```

### 5. Demonstrate Interactive Prediction

Here are examples of how the `predict_emotion` function works with various text inputs:

```python
# Demonstrate the function with example texts
example_texts = [
    "I feel wonderful today, full of joy and happiness",
    "This is so frustrating, I can't believe this happened",
    "I am scared of the dark and loud noises",
    "I love spending time with my family and friends",
    "I was completely surprised by the news",
    "I feel a deep sadness after watching that movie"
]

print("Emotion predictions for example texts:")
print("-------------------------------------")
for text in example_texts:
    predicted_emotion = predict_emotion(text)
    print(f"Text: '{text}' -> Predicted Emotion: {predicted_emotion}\n")
```

**Output of the above code:**

```
Emotion predictions for example texts:
-------------------------------------
Text: 'I feel wonderful today, full of joy and happiness' -> Predicted Emotion: joy

Text: 'This is so frustrating, I can't believe this happened' -> Predicted Emotion: sadness

Text: 'I am scared of the dark and loud noises' -> Predicted Emotion: fear

Text: 'I love spending time with my family and friends' -> Predicted Emotion: love

Text: 'I was completely surprised by the news' -> Predicted Emotion: anger

Text: 'I feel a deep sadness after watching that movie' -> Predicted Emotion: sadness
```

## Identify Correctly Classified 'Love' Texts

### Subtask:
Filter the test set (X_test) to identify texts where the true label (y_test) is 'love' (2) and the predicted label (y_pred) is also 'love' (2). Store these texts for further analysis.

**Reasoning**:
To fulfill the subtask, I will write a code block to identify correctly classified 'love' texts by filtering the test set based on matching true and predicted labels for 'love'.
"""

import numpy as np

# 1. Find the indices where both the true label is 'love' (2) AND the predicted label is 'love' (2)
correctly_classified_love_indices = np.where((y_test_arr == 2) & (y_pred_arr == 2))[0]

# 2. Extract the corresponding text samples from X_test
correctly_classified_love_texts = X_test.iloc[correctly_classified_love_indices].tolist()

# 3. Print the total number of texts correctly classified as 'love'
print(f"Total texts correctly classified as 'love': {len(correctly_classified_love_texts)}")
print("\nFirst 5 examples of correctly classified 'love' texts:")

# 4. Print the first 5 examples from the correctly_classified_love_texts list
for text in correctly_classified_love_texts[:5]:
    print(f"- {text}")

"""## Analyze Linguistic Features of Correctly Classified 'Love' Texts

### Subtask:
Extract and analyze common words and bigrams from the correctly classified 'love' texts. This involves joining the texts, tokenizing, and using Counter for frequency analysis.

**Reasoning**:
To analyze the linguistic features, I will join the correctly classified 'love' texts into a single string, tokenize them, and then use `Counter` to find and print the most common words and bigrams.
"""

from collections import Counter
from nltk.util import ngrams

# Join all correctly classified 'love' texts into a single string
all_correct_love_text = " ".join(correctly_classified_love_texts)

# Tokenize the combined text into words
words_love = all_correct_love_text.split()

# Calculate word frequency
word_counts_love = Counter(words_love)
print("\nMost common words in correctly classified 'love' texts:")
print(word_counts_love.most_common(20))

# Calculate bigram (2-word sequence) frequency
bigrams_love = list(ngrams(words_love, 2))
bigram_counts_love = Counter(bigrams_love)
print("\nMost common bigrams in correctly classified 'love' texts:")
print(bigram_counts_love.most_common(20))

"""## Compare Linguistic Features

### Subtask:
Present the most common words and bigrams for both correctly classified 'joy' and 'love' texts, allowing for a side-by-side comparison of their linguistic characteristics. This will highlight how the model distinguishes these two emotions when it makes correct predictions.

**Reasoning**:
I will present the most common words and bigrams for both correctly classified 'joy' and 'love' texts by printing the previously computed frequency counts, following the provided instructions for side-by-side comparison.
"""

print("### Linguistic Features: Correctly Classified 'Joy' vs. 'Love'\n")

print("#### Correctly Classified 'Joy' Texts\n")
print("Most common words in correctly classified 'joy' texts:")
print(word_counts_joy.most_common(20))
print("\nMost common bigrams in correctly classified 'joy' texts:")
print(bigram_counts_joy.most_common(20))

print("\n" + "-" * 70 + "\n")

print("#### Correctly Classified 'Love' Texts\n")
print("Most common words in correctly classified 'love' texts:")
print(word_counts_love.most_common(20))
print("\nMost common bigrams in correctly classified 'love' texts:")
print(bigram_counts_love.most_common(20))

print("\n" + "-" * 70 + "\n")
print("This side-by-side comparison reveals the distinct linguistic patterns the model associates with 'joy' and 'love' when making accurate predictions. These insights can inform further model improvements or feature engineering.")

texten=[
    " feel bless able spend one semester teach young adult literature",
    "feel little passionate"
]
for t in texten:
  print(predict_emotion(t))

"""## Perform Hyperparameter Tuning

### Subtask:
Execute the GridSearchCV process that was previously set up to find the optimal hyperparameters for the LinearSVC model using the training data (`X_train_tfidf`, `y_train`). This will involve fitting the `grid_search` object to the data.

"""

grid_search.fit(X_train_tfidf, y_train)

